version: "3"

volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local

services:

  #--------------------------------------------------
  # NodeJS API
  api:
    image: node:9.11
    working_dir: /app
    command: bash -c "npm install && npm start"
#    image: api
#    build: ./api
    depends_on:
      - mongodb
    ports:
     - "3000"
    volumes:
      - ./api:/app

  #--------------------------------------------------
  # Cache
  redis:
    image: redis:4.0
    command: --appendonly yes
    ports:
      - "6379"
    volumes:
      - redis-data:/data

  #--------------------------------------------------
  # Database
  mongodb:
    image: mongo:3.6
    ports:
      - "27017"
    volumes:
      - mongodb-data:/data/db
