version: "3"

volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local
  minio-data:
    driver: local

services:

  #--------------------------------------------------
  # NodeJS API
  api:
    image: node:13.10
    working_dir: /app
    command: npm start
    environment:
      NODE_ENV: development
    depends_on:
      - redis
      - mongodb
      - minio
    ports:
     - "3000:3000"
    volumes:
      - ./:/app

  #--------------------------------------------------
  # Cache
  redis:
    image: redis:4.0
    command: --appendonly yes
    ports:
      - "6379"
    volumes:
      - redis-data:/data

  #--------------------------------------------------
  # Database
  mongodb:
    image: mongo:3.6
    ports:
      - "27017"
    volumes:
      - mongodb-data:/data/db

  #--------------------------------------------------
  # S3
  minio:
    image: minio/minio:RELEASE.2018-05-16T23-35-33Z
    command: server /export
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/export
    environment:
      MINIO_ACCESS_KEY: "EOCHOHVUITIE1IU6EW4F"
      MINIO_SECRET_KEY: "ua6ooti2Aig0eiseeS8iu9wae6eax5Ap0wie5Yui"
