version: "3"

volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local

services:

  #--------------------------------------------------
  # NodeJS API
  api:
    image: node:13.10
    working_dir: /app
    command: npm start
    environment:
      NODE_ENV: development
    depends_on:
      - redis
      - mongodb
    ports:
     - "3000:3000"
    volumes:
      - ./:/app

  #--------------------------------------------------
  # Cache
  redis:
    image: redis:4.0
    command: --appendonly yes
    ports:
      - "6379"
    volumes:
      - redis-data:/data

  #--------------------------------------------------
  # Database
  mongodb:
    image: mongo:3.6
    ports:
      - "27017"
    volumes:
      - mongodb-data:/data/db
